;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		beginning-of-visual-line
		cua--prefix-override-handler
		cua-cut-region
		cua-exchange-point-and-mark
		cua-paste
		cua-set-rectangle-mark
		end-of-buffer
		end-of-visual-line
		helm-M-x
		kill-visual-line
		org-self-insert-command
		))

(setq mc/cmds-to-run-once
      '(
		comment-region
		electric-newline-and-maybe-indent
		))
